/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-data-jpa:2.7.4")
    implementation("org.springframework.boot:spring-boot-starter-data-rest:2.7.4")
    implementation("org.springframework.boot:spring-boot-starter-web:2.7.4")
    implementation("org.projectlombok:lombok:1.18.24")
    implementation("io.springfox:springfox-boot-starter:3.0.0")
    implementation("io.springfox:springfox-swagger-ui:3.0.0")
    implementation("org.springframework.kafka:spring-kafka:2.9.1")
    implementation("org.apache.kafka:kafka-clients:3.1.2")
    runtimeOnly("com.h2database:h2:2.1.214")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.7.4")
    testImplementation("junit:junit:4.13.2")
    testImplementation("org.springframework.kafka:spring-kafka-test:2.8.9")
}

group = "com.msa"
version = "0.0.1-SNAPSHOT"
description = "doldol-book"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
